{ bitcoin = "3D7rmAYgbDnp4gp4rf22THsGt74fNucPDU"
, coinbase = "mstksg"
, email = "justin@jle.im"
, gPlus = "+JustinLe"
, github = "mstksg"
, keybase = "mstksg"
, linkedIn = "lejustin"
, name = "Justin Le"
, patreon = "justinle"
, rel = "https://plus.google.com/107705320197444500140"
, twitch = "justin_l"
, twitter = "mstk"
}