{ name     = "Justin Le"
, email    = "justin@jle.im"
, rel      = "https://plus.google.com/107705320197444500140"
, twitter  = "mstk"
, gPlus    = "+JustinLe"
, github   = "mstksg"
, linkedIn = "lejustin"
, keybase  = "mstksg"
, coinbase = "mstksg"
, bitcoin  = "3D7rmAYgbDnp4gp4rf22THsGt74fNucPDU"
, patreon  = "justinle"
, twitch   = "justin_l"
}
