name: "Cachix"
on:
  pull_request:
  push:
jobs:
  cache:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Free Disk Space
      uses: insightsengineering/free-disk-space@v1.1.0
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v13
      with:
        name: mstksg
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: nix develop . --command bash -c "echo OK"
